### ISSUE TITLE
https://push.chatsecure.org/api/v1/ not working

### ISSUE THREAD

**Issue by erdii** [ChatSecure/ChatSecure-Push-Server#8]
When trying to connect I get: 

```
Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

and my ChatSecure Clients cannot subsribe to push notifications.

Is it possible to self-host the push-gateway or are ChatSecure and THIS gateway coupled together?

**Comment by erdii** [comment]
Hey :) Thanks for checking! Let me retry...

It loads very long, sometimes it renders, and sometimes I get the Application error.

My phone shows this every time I try:
![18-05-08 20-02-15 0231](https://user-images.githubusercontent.com/5539202/39775856-5db015b4-52ff-11e8-9831-bc93b4f72f9d.png)

**Comment by erdii** [comment]
I'd offer a you a vps instance if your heroku instance is too small!

**Comment by chrisballinger** [comment]
Yeah to host your own API server you'll need another app. You'll also need a GPL "additional permission" from me to legally distribute a derivative work on the App Store. Please contact me directly if you want more information about that.

**Comment by erdii** [comment]
I will contact you in the near future when i have more free time!
